### ISSUE TITLE
supporterlevels.txt not working  *RESOLVED*

### ISSUE THREAD

**Issue by drunkenslang** [novskey/novabot#6]
I've been trying to get supporter levels to work and I can't.  I have the right role ID because I'm Admin and I can do !reload.  So I used that role id and this doesn't do anything.  The log says it loaded the supporterlevels.txt but I'm still limited to what's in the config. 

332008253456932930 = [5,5,5]//Admin

**Comment by novskey** [comment]
Thanks mate, are you on the support discord? Easier to help debug there

**Comment by drunkenslang** [comment]
I can't find the link to your discord.  I'll gladly join

**Comment by novskey** [comment]
https://discord.gg/P3qrvkp

**Comment by drunkenslang** [comment]
Thanks will join when I get home.  I have a few user asking for this so I'd like to get it working.

**Comment by novskey** [comment]
No worries mate, will do what I can to get it set up for you :)
